-- Neovim icon highlights for matte-black theme
-- This file is auto-generated by themes-set-neovim-icons.sh

local M = {}

M.setup = function()
  local icon_colors = {
    -- Directories
    ["folder"] = "#4d4d4d",
    ["folder-config"] = "#666666",
    ["folder-git"] = "#e68e0d",
    ["folder-home"] = "#eaeaea",
    ["folder-downloads"] = "#e68e0d",
    ["folder-documents"] = "#eaeaea",
    ["folder-music"] = "#808080",
    ["folder-pictures"] = "#ffc107",
    ["folder-videos"] = "#e68e0d",
    
    -- Files by extension
    ["lua"] = "#4d4d4d",
    ["javascript"] = "#ffc107",
    ["typescript"] = "#4d4d4d",
    ["json"] = "#666666",
    ["markdown"] = "#eaeaea",
    ["txt"] = "#737373",
    ["bash"] = "#e68e0d",
    ["zsh"] = "#e68e0d",
    ["python"] = "#4d4d4d",
    ["rust"] = "#e67e80",
    ["go"] = "#4d4d4d",
    ["c"] = "#666666",
    ["cpp"] = "#4d4d4d",
    ["css"] = "#666666",
    ["scss"] = "#d699b6",
    ["html"] = "#e67e80",
    ["yaml"] = "#e68e0d",
    ["toml"] = "#666666",
    ["conf"] = "#737373",
    ["mp3"] = "#808080",
    ["flac"] = "#a7c080",
    ["jpg"] = "#ffc107",
    ["png"] = "#ffc107",
    ["gif"] = "#d699b6",
    ["pdf"] = "#e67e80",
    ["zip"] = "#ffc107",
  }
  
  -- Set highlights for mini.icons
  for name, color in pairs(icon_colors) do
    vim.api.nvim_set_hl(0, "MiniIcons" .. name:gsub("^%l", string.upper):gsub("-(%l)", string.upper), { fg = color })
  end
end

return M
