$color = rgba(255, 83, 69, 1.0)
$inner_color = rgba(17, 28, 24, 0.8)
$outer_color = rgba(210, 104, 156, 1.0)
$font_color = rgba(193, 196, 151, 1.0)
$check_color = rgba(84, 158, 106, 1.0)
$col_active_border = rgba(FF5345ee) rgba(D2689Cee) 45deg
$col_inactive_border = rgba(23372Baa)
