$activeBorderColor = rgba(bd93f9ee) rgba(ff79c6ee) 45deg
$inactiveBorderColor = rgba(6272a4aa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
}

