#########################################################################
### AUTOSTART ###

exec-once = waybar
exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = insync start
exec-once = wl-paste --watch cliphist store
exec-once = bash -c "sleep 10 && sshfs seb@192.168.2.199:/mnt/external /mnt/pie"
exec-once = [workspace 1 silent] $notes
exec-once = [workspace 2 silent] $browser1
exec-once = [workspace 5 silent] $editor
exec-once = [workspace 10 silent] $browser3
exec-once = [workspace 10 silent] $terminal -e btop