# Autostart 

exec-once = bash -c "waybar && sleep 120 && pkill -SIGUSR2 waybar"
exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = insync start
exec-once = wl-paste --watch cliphist store
exec-once = bash -c "sleep 10 && sshfs seb@192.168.2.199:/mnt/external /mnt/pie"
exec-once = [workspace 1 silent] obsidian --enable-features=UseOzonePlatform --ozone-platform-hint=wayland
exec-once = [workspace 2 silent] brave
exec-once = [workspace 5 silent] nvim ~/.config/hypr/
exec-once = [workspace 10 silent] btop
exec-once = [workspace 10 silent] brave --app="https://soundcloud.com/"
exec-once = [workspace 10 silent] brave --app="https://home.google.com/u/1/"
