hl.on("hyprland.start", function()
    hl.exec_cmd("xrandr --output DP-1 --primary")
    hl.exec_cmd("mako")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("~/.local/bin/walker-launch.sh --prewarm")
    hl.dispatch(hl.dsp.exec_cmd("brave --disable-features=WaylandWpColorManagerV1", { workspace = "2" }))
    hl.dispatch(hl.dsp.exec_cmd("obsidian", { workspace = "6 silent" }))
    hl.dispatch(hl.dsp.exec_cmd("ghostty -e btop", { workspace = "10 silent" }))
    hl.dispatch(hl.dsp.exec_cmd("firefox", { workspace = "10 silent" }))
    hl.exec_cmd("bash -c 'sleep 10 && waybar'")
    hl.exec_cmd("bash -c 'sleep 20 && insync start --qt-qpa-platform=xcb'")
end)
