# Autostart

exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = insync start
exec-once = wl-paste --watch cliphist store
#exec-once = bash -c "sleep 10 && sshfs seb@192.168.2.199:/mnt/external /mnt/pie"
exec-once = [workspace 1 silent] obsidian --enable-features=UseOzonePlatform --ozone-platform-hint=wayland
exec-once = [workspace 2] brave --disable-features=WaylandWpColorManagerV1
exec-once = [workspace 10 silent] ghostty -e btop
exec-once = [workspace 10 silent] firefox
exec-once = waybar