#########################################################################
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/windows.conf


#########################################################################
### PROGRAMS ###

$terminal      = ghostty
$filemanager   = thunar
$menu          = fuzzel
$editor        = /usr/local/bin/cursor.AppImage --enable-features=UseOzonePlatform --ozone-platform-hint=wayland
$imageeditor   = /usr/local/bin/gimp.AppImage
$tuieditor     = $terminal -e nvim
$clipboard     = cliphist list | fuzzel -d --width=50 | cliphist decode | wl-copy
$keybinds      = bash ~/.config/scripts/keybinds.sh
$browser1      = brave
$browser2      = brave --incognito
$browser3      = firefox
$lockcommand   = hyprlock
$colourpicker  = hyprpicker -al
$calculator    = qalculate-gtk
$assistant     = $browser1 --app="https://grok.com"
$calendar      = $browser1 --app="https://calendar.google.com/calendar/u/0/r/year"
$googlechat    = $browser1 --app="https://mail.google.com/chat/u/0/"
$iplayer       = $browser1 --app="https://www.bbc.co.uk/iplayer/episodes/b006mj59/top-gear"
$notes         = obsidian --enable-features=UseOzonePlatform --ozone-platform-hint=wayland
$nextwall      = bash ~/.config/scripts/wallpaper.sh next
$prevwall      = bash ~/.config/scripts/wallpaper.sh prev
$wallmenu      = bash ~/.config/scripts/wallpaper.sh select
$themeswitch   = bash ~/.config/scripts/themes.sh
$tmux          = $terminal -e ssh 192.168.2.200 -t "tmux attach-session"


#########################################################################
### ENVIRONMENT VARIABLES ###
