# The Wallpaper.sh script is expected to take over
preload = /home/seb/.themes/matte-black/backgrounds/2-matte-black-hands.jpg
wallpaper = ,/home/seb/.themes/matte-black/backgrounds/2-matte-black-hands.jpg

# Set to false if you are not using hyprpaper's own IPC features
ipc = on
