# The Wallpaper.sh script is expected to take over
preload = /home/seb/.themes/matte-black/backgrounds/1-matte-black.jpg
wallpaper = ,/home/seb/.themes/matte-black/backgrounds/1-matte-black.jpg

# Set to false if you are not using hyprpaper's own IPC features
ipc = on
