# The Wallpaper.sh script is expected to take over
preload = /home/seb/.themes/dracula/wallpapers/1_neon_street.png
wallpaper = ,/home/seb/.themes/dracula/wallpapers/1_neon_street.png

# Set to false if you are not using hyprpaper's own IPC features
ipc = on
