#########################################################################
### INPUT ###

input {
    kb_layout = gb
    follow_mouse = 1
    sensitivity = 1.2
    numlock_by_default = true
    scroll_factor = 1.2
}

gestures {
    workspace_swipe = false
}

xwayland {
    force_zero_scaling = true
}