hl.monitor({ output = "HDMI-A-2", mode = "2560x1440", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-1", mode = "3840x2160", position = "2560x0", scale = 1.5 })
hl.monitor({ output = "DP-2", mode = "2560x1440", position = "5120x0", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "2560x1440", position = "2560x-1440", scale = 1 })

hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "2", monitor = "DP-1" })
hl.workspace_rule({ workspace = "3", monitor = "DP-2" })
hl.workspace_rule({ workspace = "4", monitor = "DP-1" })
hl.workspace_rule({ workspace = "5", monitor = "DP-1" })
hl.workspace_rule({ workspace = "6", monitor = "DP-1" })
hl.workspace_rule({ workspace = "7", monitor = "DP-1" })
hl.workspace_rule({ workspace = "8", monitor = "DP-1" })
hl.workspace_rule({ workspace = "9", monitor = "DP-1" })
hl.workspace_rule({ workspace = "0", monitor = "HDMI-A-1" })
