             ##############
             #  HDMI-A-1  #
             #     0      #
########################################
#  HDMI-A-2  #    DP-1    #    DP-2    #
#    1 4 7   #   2 5 8    #   3 6 9    #
########################################

monitor = HDMI-A-2, 2560x1440, 0x0, 1
monitor = DP-1, 3840x2160, 2560x0, 1.5
monitor = DP-2, 2560x1440, 5120x0, 1
monitor = HDMI-A-1, 2560x1440, 2560x-1440, 1

# Workspaces
workspace = 1, monitor:HDMI-A-2
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-1 
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 0, monitor:HDMI-A-1