# Floating windows
windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 800 600, tag:floating-window
windowrule = tag +floating-window, class:(qalculate-gtk|Wiremix|brave-calendar.google.com__calendar_u_0_r_year-Default|TUI.float)
windowrule = tag +floating-window, title:^(Open.*Files?|Save.*Files?|Save.*As|All Files|Save)

# Transparency
windowrulev2 = opacity 1 override 1 override, class:^(mpv|imv|imv-dir)$
windowrulev2 = opacity 1 override 1 override, title:^(.*Picture-in-Picture.*|.*Google Home.*|.*YouTube.*)$
windowrulev2 = opacity 0.95 override 0.9 override, class:^(com.mitchellh.ghostty)$

# General
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = workspace 10, class:^(firefox)$
windowrulev2 = size 1220 940, initialClass:^(brave-calendar.google.com__calendar_u_0_r_year-Default)$
