# General
windowrule = suppressevent maximize, class:.*

# Floating windows
windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 1024 768, tag:floating-window
windowrule = tag +floating-window, class:(qalculate-gtk|insync|brave-calendar.*|brave-mail.*|TUI.float)
windowrule = tag +floating-window, title:^(.*Sign in.*|Untitled.*)
windowrule = tag +floating-window, title:^(Rename.*|Open.*Files?|Save.*Files?|Save.*As|.*wants to save.*|.*wants to open.*|Export Image.*)
windowrule = tag +floating-window, title:^(.*Channel 4.*|.*iplayer.*)
windowrule = tile, class:^(TUI.tiled)$

# Transparency
windowrule = opacity 1 1 override, class:^(mpv|imv|imv-dir)$
windowrule = opacity 1 1 override, title:^(.*Picture-in-Picture.*|.*Google Home.*|.*YouTube.*|.*Channel 4.*|.*iplayer.*)