# General
# windowrule = suppressevent maximize, match:class .*

# Floating windows
windowrule = float 1, match:tag floating-window
windowrule = center 1, match:tag floating-window
windowrule = size 1600 900, match:tag floating-window
windowrule = tag +floating-window, match:class (insync|brave-calendar.*|brave-mail.*|TUI.float)
windowrule = tag +floating-window, match:title ^(.*Sign in.*|Untitled.*)
windowrule = tag +floating-window, match:title ^(Rename.*|Open.*Files?|Save.*Files?|Save.*As|.*wants to save.*|.*wants to open.*|Export Image.*)
windowrule = tag +floating-window, match:title ^(.*channel4.*|.*iplayer.*|.*youtube.*)
windowrule = tile 1, match:class ^(TUI.tiled)$

# Transparency
windowrule = opacity 1 1 override, match:class ^(mpv|imv|imv-dir)$
windowrule = opacity 1 1 override, match:title ^(.*Picture-in-Picture.*|.*www.channel4.com.*|.*My4.*|.*iplayer.*)

# Workspaces
windowrule = workspace 8, match:initial_class ^(gimp)
windowrule = workspace 10, match:initial_title ^(soundcloud.com_/|home.google.com_/u/1/)
