-- Neovim icon highlights for everforest theme
-- This file is auto-generated by themes-set-neovim-icons.sh

local M = {}

M.setup = function()
  local icon_colors = {
    -- Directories
    ["folder"] = "#7fbbb3",
    ["folder-config"] = "#7fbbb3",
    ["folder-git"] = "#e69875",
    ["folder-home"] = "#d3c6aa",
    ["folder-downloads"] = "#e69875",
    ["folder-documents"] = "#d3c6aa",
    ["folder-music"] = "#d699b6",
    ["folder-pictures"] = "#e69875",
    ["folder-videos"] = "#e69875",
    
    -- Files by extension
    ["lua"] = "#7fbbb3",
    ["javascript"] = "#e69875",
    ["typescript"] = "#7fbbb3",
    ["json"] = "#d3c6aa",
    ["markdown"] = "#d3c6aa",
    ["txt"] = "#d699b6",
    ["bash"] = "#e69875",
    ["zsh"] = "#e69875",
    ["python"] = "#a7c080",
    ["rust"] = "#e67e80",
    ["go"] = "#7fbbb3",
    ["c"] = "#d3c6aa",
    ["cpp"] = "#7fbbb3",
    ["css"] = "#83c092",
    ["scss"] = "#d699b6",
    ["html"] = "#e67e80",
    ["yaml"] = "#e69875",
    ["toml"] = "#7fbbb3",
    ["conf"] = "#d699b6",
    ["mp3"] = "#d699b6",
    ["flac"] = "#a7c080",
    ["jpg"] = "#e69875",
    ["png"] = "#e69875",
    ["gif"] = "#d699b6",
    ["pdf"] = "#e67e80",
    ["zip"] = "#e69875",
  }
  
  -- Set highlights for mini.icons
  for name, color in pairs(icon_colors) do
    vim.api.nvim_set_hl(0, "MiniIcons" .. name:gsub("^%l", string.upper):gsub("-(%l)", string.upper), { fg = color })
  end
end

return M
