background = #0a0e19
foreground = #f8f8f2
cursor-color = #f8f8f2
selection-background = #f8f8f2
selection-foreground = #0a0e19

palette = 0=#282a36
palette = 1=#ff5555
palette = 2=#50fa7b
palette = 3=#ffb86c
palette = 4=#8be9fd
palette = 5=#bd93f9
palette = 6=#b2f8f8
palette = 7=#f8f8f2
palette = 8=#6272a4
palette = 9=#ff5555
palette = 10=#50fa7b
palette = 11=#ffb86c
palette = 12=#8be9fd
palette = 13=#ff79c6
palette = 14=#b2f8f8
palette = 15=#f8f8f2
