$color = rgba(188, 198, 224, 1.0)
$inner_color = rgba(239, 241, 245, 0.8)
$outer_color = rgba(138, 173, 244, 1.0)
$font_color = rgba(76, 79, 105, 1.0)
$check_color = rgba(64, 160, 43, 1.0)
$col_active_border = rgba(1e66f5ee) rgba(8839efee) 45deg
$col_inactive_border = rgba(4c4f69aa)
